### ISSUE TITLE
How to split multiple-page tif image?

### ISSUE THREAD

**Issue by yemre-data** [yemre-data/ecoli_bacteria_detection#1]
I tried with imagemagick but it did not work? cv2 and pil is reading just first page(slice) of image

**Comment by maincover** [comment]
> I tried with imagemagick but it did not work? cv2 and pil is reading just first page(slice) of image

Use Image, stakc to images

**Comment by yemre-data** [comment]
from skimage import io
im = io.imread('/home/criuser/Desktop/Internship/Orginal_images/Original-s1-ss-286-roi-24.tif')
print(im.shape)

I found  a solution thank you for comment
